/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import HasA.DisneyPlus;
import SystemAndMain.VideoContentSystem;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ErayAltay
 */
public class AddVideoContentFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    RemoveSearchFrame rsf = new RemoveSearchFrame(this);

    public void fillComboBox() {
        rsf.getVideoContentNames().setModel(new DefaultComboBoxModel(VideoContentSystem.getVideoContentName()));
    }
    
    public AddVideoContentFrame() {
        initComponents();
        if (RB_animation.isSelected()) {
            RB_animation.setVisible(true);
            RB_series.setVisible(false);
            RB_short.setVisible(false);
            RB_movie.setVisible(false);
            RB_doc.setVisible(false);
        } 
        else if (RB_series.isSelected()) {
            RB_animation.setVisible(false);
            RB_series.setVisible(true);
            RB_short.setVisible(false);
            RB_movie.setVisible(false);
            RB_doc.setVisible(false);
        }
        else if(RB_short.isSelected()){
           RB_animation.setVisible(false);
            RB_series.setVisible(false);
            RB_short.setVisible(true);
            RB_movie.setVisible(false);
            RB_doc.setVisible(false);
        }
        else if(RB_doc.isSelected()){
            RB_animation.setVisible(false);
            RB_series.setVisible(false);
            RB_short.setVisible(false);
            RB_movie.setVisible(false);
            RB_doc.setVisible(true);
        }
        else if(RB_movie.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(true);
            DocPanel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RB_animation = new javax.swing.JRadioButton();
        RB_short = new javax.swing.JRadioButton();
        RB_doc = new javax.swing.JRadioButton();
        RB_series = new javax.swing.JRadioButton();
        RB_movie = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        TF_name = new javax.swing.JTextField();
        TF_publisher = new javax.swing.JTextField();
        TF_director = new javax.swing.JTextField();
        AnimationPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_prodYear = new javax.swing.JTextField();
        DocPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_runtimeDoc = new javax.swing.JTextField();
        ShortFilmPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RB_teen = new javax.swing.JRadioButton();
        RB_mature = new javax.swing.JRadioButton();
        SeriesPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TF_numOfEpisode = new javax.swing.JTextField();
        TF_runtimeSeries = new javax.swing.JTextField();
        MoviePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TF_runtimeMovie = new javax.swing.JTextField();
        checkBoxAward = new javax.swing.JCheckBox();
        checkBoxNominate = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CB_whereToWatch = new javax.swing.JComboBox<>();
        TF_subMonths = new javax.swing.JTextField();
        CB_subPlan = new javax.swing.JComboBox<>();
        displayBtn = new javax.swing.JButton();
        removeSearchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Video Content");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setText("Publisher:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setText("Director:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        buttonGroup1.add(RB_animation);
        RB_animation.setText("Animation");
        RB_animation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_animationActionPerformed(evt);
            }
        });
        getContentPane().add(RB_animation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        buttonGroup1.add(RB_short);
        RB_short.setText("Short Film");
        RB_short.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_shortActionPerformed(evt);
            }
        });
        getContentPane().add(RB_short, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        buttonGroup1.add(RB_doc);
        RB_doc.setText("Documentary");
        RB_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_docActionPerformed(evt);
            }
        });
        getContentPane().add(RB_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        buttonGroup1.add(RB_series);
        RB_series.setText("Series");
        RB_series.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_seriesActionPerformed(evt);
            }
        });
        getContentPane().add(RB_series, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        buttonGroup1.add(RB_movie);
        RB_movie.setText("Movie");
        RB_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_movieActionPerformed(evt);
            }
        });
        getContentPane().add(RB_movie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel4.setText("Genre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        TF_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nameActionPerformed(evt);
            }
        });
        TF_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TF_nameKeyPressed(evt);
            }
        });
        getContentPane().add(TF_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, -1));

        TF_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_publisherActionPerformed(evt);
            }
        });
        getContentPane().add(TF_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, -1));

        TF_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_directorActionPerformed(evt);
            }
        });
        getContentPane().add(TF_director, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 150, -1));

        jLabel5.setText("Production Year:");

        jLabel6.setText("Animation");

        javax.swing.GroupLayout AnimationPanelLayout = new javax.swing.GroupLayout(AnimationPanel);
        AnimationPanel.setLayout(AnimationPanelLayout);
        AnimationPanelLayout.setHorizontalGroup(
            AnimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimationPanelLayout.createSequentialGroup()
                .addGroup(AnimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnimationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF_prodYear))
                    .addGroup(AnimationPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6)
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AnimationPanelLayout.setVerticalGroup(
            AnimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnimationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(AnimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_prodYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(AnimationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 80));

        jLabel7.setText("Documentary");

        jLabel8.setText("Runtime:");

        javax.swing.GroupLayout DocPanelLayout = new javax.swing.GroupLayout(DocPanel);
        DocPanel.setLayout(DocPanelLayout);
        DocPanelLayout.setHorizontalGroup(
            DocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TF_runtimeDoc)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DocPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26))
        );
        DocPanelLayout.setVerticalGroup(
            DocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(DocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_runtimeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(DocPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 130, -1));

        jLabel9.setText("Short Film");

        jLabel10.setText("Rating:");

        buttonGroup2.add(RB_teen);
        RB_teen.setText("Teen");
        RB_teen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_teenActionPerformed(evt);
            }
        });

        buttonGroup2.add(RB_mature);
        RB_mature.setText("Mature");
        RB_mature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_matureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShortFilmPanelLayout = new javax.swing.GroupLayout(ShortFilmPanel);
        ShortFilmPanel.setLayout(ShortFilmPanelLayout);
        ShortFilmPanelLayout.setHorizontalGroup(
            ShortFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShortFilmPanelLayout.createSequentialGroup()
                .addGroup(ShortFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShortFilmPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9))
                    .addGroup(ShortFilmPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ShortFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB_mature)
                            .addComponent(RB_teen))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ShortFilmPanelLayout.setVerticalGroup(
            ShortFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShortFilmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(ShortFilmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(RB_teen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_mature)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(ShortFilmPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel11.setText("Series");

        jLabel12.setText("Number of Episodes:");

        jLabel13.setText("Episode Runtime:");

        javax.swing.GroupLayout SeriesPanelLayout = new javax.swing.GroupLayout(SeriesPanel);
        SeriesPanel.setLayout(SeriesPanelLayout);
        SeriesPanelLayout.setHorizontalGroup(
            SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesPanelLayout.createSequentialGroup()
                .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeriesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_runtimeSeries, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(TF_numOfEpisode)))
                    .addGroup(SeriesPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        SeriesPanelLayout.setVerticalGroup(
            SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TF_numOfEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TF_runtimeSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(SeriesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 190, -1));

        jLabel14.setText("Movie");

        jLabel15.setText("Runtime:");

        checkBoxAward.setText("Awarded");
        checkBoxAward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAwardActionPerformed(evt);
            }
        });

        checkBoxNominate.setText("Nominated");
        checkBoxNominate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNominateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MoviePanelLayout = new javax.swing.GroupLayout(MoviePanel);
        MoviePanel.setLayout(MoviePanelLayout);
        MoviePanelLayout.setHorizontalGroup(
            MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MoviePanelLayout.createSequentialGroup()
                        .addComponent(checkBoxAward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxNominate))
                    .addGroup(MoviePanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MoviePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(MoviePanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TF_runtimeMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        MoviePanelLayout.setVerticalGroup(
            MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TF_runtimeMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxAward)
                    .addComponent(checkBoxNominate))
                .addGap(23, 23, 23))
        );

        getContentPane().add(MoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel16.setText("Disney Plus");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel17.setText("Where to Watch:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel18.setText("Subscription Plan:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        jLabel19.setText("Subscription Months:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        CB_whereToWatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV", "Mobile", "Web" }));
        CB_whereToWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_whereToWatchActionPerformed(evt);
            }
        });
        getContentPane().add(CB_whereToWatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 100, -1));
        getContentPane().add(TF_subMonths, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 100, -1));

        CB_subPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard ($10)", "Family ($15)", "Lite ($5)" }));
        CB_subPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_subPlanActionPerformed(evt);
            }
        });
        getContentPane().add(CB_subPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        displayBtn.setText("DISPLAY");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(displayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 200, -1));

        removeSearchBtn.setText("REMOVE/SEARCH");
        removeSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 200, -1));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 200, -1));

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 690, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_animationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_animationActionPerformed
        // TODO add your handling code here:
        if (RB_animation.isSelected()) {
            AnimationPanel.setVisible(true);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        } 
        else if (RB_series.isSelected()) {
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(true);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_short.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(true);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_doc.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(true);
        }
        else if(RB_movie.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(true);
            DocPanel.setVisible(false);
        }
    }//GEN-LAST:event_RB_animationActionPerformed

    private void removeSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSearchBtnActionPerformed
        // TODO add your handling code here:
        if (!VideoContentSystem.getVideoContentSet().isEmpty()) {
            fillComboBox();
            rsf.setVisible(true);
            this.setVisible(false);
        }else
            TA.setText("Enter Video Content info to remove or search!");
    }//GEN-LAST:event_removeSearchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        int prodYear, runtimeDoc, numOfEpisode, runtimeSer, runtimeMovie;
        String rating;
        double disneyPlusPrice;
        boolean isAwarded=false,isNominated=false;
        boolean res = false;
        
        if(TF_name.getText().equals("")
                ||TF_publisher.getText().equals("")
                ||TF_director.getText().equals("")
                ||TF_subMonths.getText().equals("")){
            TA.setText("Fill all the fields!");
        }else{
            String name = TF_name.getText();
            String publisher = TF_publisher.getText();
            String director = TF_director.getText();
            
            String whereToWatch = CB_whereToWatch.getSelectedItem() + "";
            
            if(CB_subPlan.getSelectedIndex() == 0){
                disneyPlusPrice = 10;
            }else if(CB_subPlan.getSelectedIndex() == 1){
                disneyPlusPrice = 15;
            }else{
                disneyPlusPrice = 5;
            }
            
            int howManyMonths = Integer.parseInt(TF_subMonths.getText());
            
            
            DisneyPlus dp = new DisneyPlus(whereToWatch, disneyPlusPrice, howManyMonths);
            //String name, String publisher, String director, String genre, int runtimeMovie, boolean isAwarded, boolean isNominated, int productionYear, int runtimeDoc, int episodeNumber, int oneEpisodeRuntime, String rating
            if(RB_animation.isSelected()){
                prodYear = Integer.parseInt(TF_prodYear.getText());
                res = VideoContentSystem.addVideoContent(name, publisher, director, "Animation",dp, 0, false, false, prodYear, 0, 0, 0, "");
            }else if(RB_short.isSelected()){
                if(RB_teen.isSelected()){
                    rating = "T";
                }else{
                    rating = "M";
                }
                res = VideoContentSystem.addVideoContent(name, publisher, director, "Short Film",dp, 0, false, false, 0, 0, 0, 0, rating);
            }else if(RB_doc.isSelected()){
                runtimeDoc = Integer.parseInt(TF_runtimeDoc.getText());
                res = VideoContentSystem.addVideoContent(name, publisher, director, "Documentary",dp, 0, false, false, 0, runtimeDoc, 0, 0, "");
            }else if(RB_series.isSelected()){
                numOfEpisode = Integer.parseInt(TF_numOfEpisode.getText());
                runtimeSer = Integer.parseInt(TF_runtimeSeries.getText());
                res = VideoContentSystem.addVideoContent(name, publisher, director, "Series",dp, 0, false, false, 0, 0, numOfEpisode, runtimeSer, "");
            }else if(RB_movie.isSelected()){
                runtimeMovie = Integer.parseInt(TF_runtimeMovie.getText());
                isAwarded = checkBoxAward.isSelected();
                isNominated = checkBoxNominate.isSelected();
                res = VideoContentSystem.addVideoContent(name, publisher, director, "Movie",dp, runtimeMovie, isAwarded, isNominated, 0, 0, 0, 0, "");
            }
            
            if (res) {
                TA.setText("Video Content is added!");
            } else {
                TA.setText("Video Content is already exist! Please Try Again!");
            }
        }
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void CB_whereToWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_whereToWatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_whereToWatchActionPerformed

    private void TF_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nameActionPerformed

    private void TF_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_publisherActionPerformed

    private void TF_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_directorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_directorActionPerformed

    private void RB_shortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_shortActionPerformed
        // TODO add your handling code here:
        if (RB_animation.isSelected()) {
            AnimationPanel.setVisible(true);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        } 
        else if (RB_series.isSelected()) {
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(true);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_short.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(true);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_doc.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(true);
        }
        else if(RB_movie.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(true);
            DocPanel.setVisible(false);
        }
    }//GEN-LAST:event_RB_shortActionPerformed

    private void RB_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_docActionPerformed
        // TODO add your handling code here:
        if (RB_animation.isSelected()) {
            AnimationPanel.setVisible(true);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        } 
        else if (RB_series.isSelected()) {
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(true);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_short.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(true);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_doc.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(true);
        }
        else if(RB_movie.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(true);
            DocPanel.setVisible(false);
        }
    }//GEN-LAST:event_RB_docActionPerformed

    private void RB_seriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_seriesActionPerformed
        // TODO add your handling code here:
        if (RB_animation.isSelected()) {
            AnimationPanel.setVisible(true);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        } 
        else if (RB_series.isSelected()) {
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(true);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_short.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(true);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_doc.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(true);
        }
        else if(RB_movie.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(true);
            DocPanel.setVisible(false);
        }
    }//GEN-LAST:event_RB_seriesActionPerformed

    private void RB_movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_movieActionPerformed
        // TODO add your handling code here:
        if (RB_animation.isSelected()) {
            AnimationPanel.setVisible(true);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        } 
        else if (RB_series.isSelected()) {
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(true);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_short.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(true);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(false);
        }
        else if(RB_doc.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(false);
            DocPanel.setVisible(true);
        }
        else if(RB_movie.isSelected()){
            AnimationPanel.setVisible(false);
            SeriesPanel.setVisible(false);
            ShortFilmPanel.setVisible(false);
            MoviePanel.setVisible(true);
            DocPanel.setVisible(false);
        }
    }//GEN-LAST:event_RB_movieActionPerformed

    private void RB_teenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_teenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_teenActionPerformed

    private void RB_matureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_matureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_matureActionPerformed

    private void CB_subPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_subPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_subPlanActionPerformed

    private void checkBoxAwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxAwardActionPerformed

    private void checkBoxNominateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNominateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxNominateActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        if (!VideoContentSystem.getVideoContentSet().isEmpty()) {
            VideoContentSystem.calcNewPrice();
            TA.setText(VideoContentSystem.display());
        } else {
            TA.setText("Enter any Video Content info to display!");
        }
    }//GEN-LAST:event_displayBtnActionPerformed
  
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(evt.getButton() == MouseEvent.BUTTON2){
            displayBtn.doClick();
        }
    }//GEN-LAST:event_formMouseClicked

    private void TF_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TF_nameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            addBtn.doClick();
        }
    }//GEN-LAST:event_TF_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVideoContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVideoContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVideoContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVideoContentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVideoContentFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnimationPanel;
    private javax.swing.JComboBox<String> CB_subPlan;
    private javax.swing.JComboBox<String> CB_whereToWatch;
    private javax.swing.JPanel DocPanel;
    private javax.swing.JPanel MoviePanel;
    private javax.swing.JRadioButton RB_animation;
    private javax.swing.JRadioButton RB_doc;
    private javax.swing.JRadioButton RB_mature;
    private javax.swing.JRadioButton RB_movie;
    private javax.swing.JRadioButton RB_series;
    private javax.swing.JRadioButton RB_short;
    private javax.swing.JRadioButton RB_teen;
    private javax.swing.JPanel SeriesPanel;
    private javax.swing.JPanel ShortFilmPanel;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField TF_director;
    private javax.swing.JTextField TF_name;
    private javax.swing.JTextField TF_numOfEpisode;
    private javax.swing.JTextField TF_prodYear;
    private javax.swing.JTextField TF_publisher;
    private javax.swing.JTextField TF_runtimeDoc;
    private javax.swing.JTextField TF_runtimeMovie;
    private javax.swing.JTextField TF_runtimeSeries;
    private javax.swing.JTextField TF_subMonths;
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox checkBoxAward;
    private javax.swing.JCheckBox checkBoxNominate;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeSearchBtn;
    // End of variables declaration//GEN-END:variables
}
