/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.VideoContentSystem;
import VideoContent.VideoContent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author ErayAltay
 */
public class RemoveSearchFrame extends javax.swing.JFrame {

    AddVideoContentFrame videocontent;
    /**
     * Creates new form RemoveSearchFrame
     */
    public RemoveSearchFrame(AddVideoContentFrame v) {
        videocontent = v;
        initComponents();
    }
    
    public JComboBox getVideoContentNames() {
        return VideoContentNames;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VideoContentNames = new javax.swing.JComboBox<>();
        removeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dispTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Search");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Content Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        VideoContentNames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        VideoContentNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoContentNamesActionPerformed(evt);
            }
        });
        getContentPane().add(VideoContentNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 106, -1));

        removeBtn.setText("REMOVE");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 258, -1, -1));

        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 258, -1, -1));

        dispTA.setColumns(20);
        dispTA.setRows(5);
        jScrollPane1.setViewportView(dispTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, 354, 188));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VideoContentNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoContentNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VideoContentNamesActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        String contentName = (String)VideoContentNames.getSelectedItem();
        VideoContent res = VideoContentSystem.removeVideoContent(contentName);
        if (res != null) {
            dispTA.append("\nVideo Content is succesfully deleted!\n");
            VideoContentNames.setModel(new DefaultComboBoxModel(VideoContentSystem.getVideoContentName()));
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        dispTA.setText("");
        videocontent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> VideoContentNames;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextArea dispTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
